### ISSUE TITLE
xdg-open

### ISSUE THREAD

**Issue by 0xAF** [andrewchambers/godothecorrectthing#1]
Why not use [`xdg-open`](https://portland.freedesktop.org/doc/xdg-open.html) directly for everything. Instead of defining `browser`, `editor` and `filemanager`?
With `xdg-open` it will be more flexible, since it can open different link types or file types, without the need to detect what action to take in script.
Perhaps you will need to detect the action for the editor only, because of the file-position parameter...

btw, there is something to fix on this line:
./godothecorrectthing.sh: line 74: f: unbound variable

**Comment by andrewchambers** [comment]
You are right.

Thanks for the report, not sure how that slipped in, must have forgot to push from my laptop. I added xdg-open too.
